// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ0ZZFLSFlq2SBkPFJPXtn5fNXhGipTBA',
    appId: '1:592894262862:web:184ed238f41696d9dd8d1f',
    messagingSenderId: '592894262862',
    projectId: 'pickme-d31b7',
    authDomain: 'pickme-d31b7.firebaseapp.com',
    storageBucket: 'pickme-d31b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ59aK-hAtYDUdLTPO-1qEVNmHSdBT1dw',
    appId: '1:592894262862:android:bdaf117efba336b1dd8d1f',
    messagingSenderId: '592894262862',
    projectId: 'pickme-d31b7',
    storageBucket: 'pickme-d31b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCSX3jAsjvNiqyVo-_fw34bZYmhhmGRYI',
    appId: '1:592894262862:ios:2c64fe375a1b7c05dd8d1f',
    messagingSenderId: '592894262862',
    projectId: 'pickme-d31b7',
    storageBucket: 'pickme-d31b7.firebasestorage.app',
    iosBundleId: 'com.example.pickmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCSX3jAsjvNiqyVo-_fw34bZYmhhmGRYI',
    appId: '1:592894262862:ios:2c64fe375a1b7c05dd8d1f',
    messagingSenderId: '592894262862',
    projectId: 'pickme-d31b7',
    storageBucket: 'pickme-d31b7.firebasestorage.app',
    iosBundleId: 'com.example.pickmeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ0ZZFLSFlq2SBkPFJPXtn5fNXhGipTBA',
    appId: '1:592894262862:web:a2012d5b8b67500cdd8d1f',
    messagingSenderId: '592894262862',
    projectId: 'pickme-d31b7',
    authDomain: 'pickme-d31b7.firebaseapp.com',
    storageBucket: 'pickme-d31b7.firebasestorage.app',
  );
}
